name: Hello World
on: [push]

jobs:
    hello-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4 
        - name: Hello world
          run: echo "Hello, Nik!" > hello.txt
        - name: Archive
          uses: actions/upload-artifact@v4
          with:
            name: hello-artifact
            path: hello.txt

    download:
        runs-on: ubuntu-latest
        needs: hello-job
        steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: hello-artifact
            path: ./artifacts
        - name: List files
          run: cat ./artifacts/hello.txt