name: Matrix_Flow_Multi_Image
on: 
  workflow_dispatch:

jobs:
    deploy:
      strategy:
        fail-fast: false
        max-parallel: 2
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-latest]
          image: [hello-world, alpine]
          exclude:
            - os: windows-latest
              image: alpine
          include:
            - os: ubuntu-latest
              image: amd64/alpine
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4 
        - name: Display Docker Details
          run: docker info
        - name: Run Image on ${{ matrix.os }}
          run: docker run ${{ matrix.image }}

